# Generated by Django 3.0.3 on 2020-03-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('subject', '0002_rework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='subject',
            name='courses',
            field=models.ManyToManyField(to='faculty.Course'),
        ),
        migrations.AlterField(
            model_name='rework',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Created'), (20, 'Approved'), (30, 'Rejected'), (40, 'Reworked'), (50, 'Expired')], default=10),
        ),
    ]
