# Generated by Django 3.0.3 on 2020-03-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_load_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rework',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Created'), (20, 'Approved'), (30, 'Rejected'), (40, 'Reworked'), (50, 'Expired')], default=10),
        ),
    ]
